### ISSUE TITLE
No skull owner when using /crate additem

### ISSUE THREAD

**Issue by nicknickeryt** [Zarosch/Crates#8]
Server version: 1.16.4
Plugin version: latest (1.14)

When you try to add a player skull using /crate additem, the owner's metadata is lost, so it resets back to Steve.
Example here: https://youtu.be/yVNJ_CJEIsM

crates.yml looks like this:

```
  test:
    name: test Crate
    item:
      material: DRAGON_EGG
      amount: 1
      durability: 0
      meta:
        displayName: test test
        showenchant: false
      enchantments:
        unsafe:
        - LUCK:1
    type: crate
    content:
      1609248904660-873-1:
        name: §fSkull of santa
        chance: 1
        item:
          material: PLAYER_HEAD
          amount: 1
          durability: 3
          meta:
            displayName: §fSkull of santa
        items:
          item:
            material: PLAYER_HEAD
            amount: 1
            durability: 3
            meta:
              displayName: §fSkull of santa
        commands: []
```
There should be 'owningPlayer' section, but for some reason it's not being created.
